# Generated by Django 3.2.5 on 2021-07-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuerate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bpmtest',
            fields=[
                ('tid', models.BigAutoField(db_column='TID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'BPMTEST',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movielove',
            fields=[
                ('lid', models.BigAutoField(db_column='LID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'MOVIELOVE',
                'managed': False,
            },
        ),
    ]
